### ISSUE TITLE
Cannot precompute input

### ISSUE THREAD

**Issue by n-getty** [nengo/nengo-loihi#108]
I am defining the nengo model below (converting a keras model using nengo-extras):

```
with nengo.Network() as model:
    u = nengo.Node(nengo.processes.PresentInput(X_test, presentation_time))
    knet = SequentialNetwork(kmodel, synapse=nengo.synapses.Alpha(0.005))
    nengo.Connection(u, knet.input)

    input_p = nengo.Probe(u)
    output_p = nengo.Probe(knet.output)
```

No issue running the nengo simulator. However if I try to precompute with the nengo-loihi simulator:

```
with Sim(model, precompute=True) as sim:
    sim.run(n_presentations * presentation_time)
```

I get the following exception:

```
Traceback (most recent call last):
  File "...", line 249, in <module>
    with Sim(model, precompute=True) as sim:
  File ".../python3.6/site-packages/nengo_loihi/simulator.py", line 166, in __init__
    host_pre = splitter.split_pre_from_host(host)
  File ".../python3.6/site-packages/nengo_loihi/splitter.py", line 322, in split_pre_from_host
    raise Exception('Cannot precompute input, '
Exception: Cannot precompute input, as it is dependent on output

```

It may not be necessary to precompute but I am curious what I may be doing incorrectly here, thanks.

**Comment by drasmuss** [comment]
The `nengo-extras` deep learning package uses `Nodes` to implement most of the layer types.  And any time you have a network architecture that looks like `... -> Ensemble -> Node -> Ensemble -> ...`, that network will not be precomputable.  Precomputing basically means that all the `Node` outputs are calculated before the simulation starts, but with that architecture that isn't possible (because we need to know the output of the first `Ensemble` to know what the output of the `Node` will be).  So you aren't doing anything incorrectly, it's just the nature of the way `nengo-extras` converts a network that means those networks will most likely not be precomputable.

**Comment by drasmuss** [comment]
Closing this as I believe it is resolved, but let us know if not and we can reopen.
