### ISSUE TITLE
test_installer_called_twice fails for certain log levels

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-loihi#196]
To reproduce, run:
```
py.test --fulltrace --log-level=INFO nengo_loihi/builder/tests/test_nengo_dl.py::test_installer_called_twice
```

```
...
        with caplog.at_level(logging.DEBUG):
            install()
>       assert [rec.message for rec in caplog.records] == [
            "NengoDL neuron builders already installed",
        ]
E       AssertionError: assert [] == ['NengoDL neuron builders already installed']
E         Right contains more items, first extra item: 'NengoDL neuron builders already installed'
E         Use -v to get the full diff

nengo_loihi/builder/tests/test_nengo_dl.py:27: AssertionError
```

It also happens with `--log-level=WARNING`, but it does _not_ happen with `log-level=DEBUG`. The problem something to do with the way in which the test attempts to capture logging information at a particular level.

**Comment by drasmuss** [comment]
While this is definitely a bug, since it only affects the test suite (and only in a pretty particular case) it's so far down the priority queue that, if we're being honest, it probably won't be worked on/fixed any time soon. So closing to reflect the fact that we have no plans to fix this (while acknowledging that it should be fixed in an ideal world 😉).
