### ISSUE TITLE
Unimplemented Error: Generic conv implementation only supports NHWC tensor format for now.

### ISSUE THREAD

**Issue by wssrc** [nengo/nengo-loihi#239]
When trying following the CNN tutorial to classify cats vs dogs, the code breaks with the above code when I set `do_training=True`. It breaks on the line
`with nengo_dl.Simpulator(net,....) as sim:
   if do_training:
        sim.loss(test_data_dict, ...)` 
 I have nengo v3.0.0, nengo_loihi v0.8.0, nengo_dl v2.1.1 I suspect this is because nengo v3.0.0 is unreleased, so this is more a request for you guys to implement this :)

**Comment by tbekolay** [comment]
Hi @wssrc! This might be an issue with dev versions, but in the past when we've gotten the "Unimplemented Error: Generic conv implementation only supports NHWC tensor format for now" error, it's because Nengo DL's convolution implementation uses some features of TensorFlow that are only available with `tensorflow-gpu` and not the CPU-based `tensorflow`. Which one are you using at the moment?

**Comment by wssrc** [comment]
I think I'm using tensorflow since it keeps recommending that I install tensorflow-gpu. But I do have it installed, so I don't know what's up with that. Do you have any suggestions? That may have been my problem

**Comment by tbekolay** [comment]
I've had troubles installing tensorflow in the past, so I don't know if I can be of much help, but I guess my generic recommendation would be to try to remove all of the existing tensorflow installations (i.e., do `pip uninstall tensorflow tensorflow-gpu` a few times to make sure they're all removed) then reinstall `tensorflow-gpu`.
