### ISSUE TITLE
Installation documentation out of sync

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-loihi#244]
After #240 the [installation documentation](https://www.nengo.ai/nengo-loihi/installation.html) should mention both scipy and numpy.

In addition, the instructions refer to `nxsdk==0.8.1` in a number of places, when that version is no longer supported (currently only `0.8.5` is supported)?

**Comment by drasmuss** [comment]
Where are you thinking about referring to scipy?  We refer to numpy because it should be slightly faster when installed through conda, but installing scipy through pip or conda shouldn't make a difference.  We don't explicitly list out all the requirements in that document (as they should all just be installed through `pip install nengo-loihi`) E.g. we also require `jinja`, but I don't think that needs to be explicitly mentioned either.

But we should definitely update the `nxsdk` version.

**Comment by arvoelke** [comment]
Didn't look too thoroughly but comments like:

> If anything goes wrong during this process, it is likely related to installing NumPy.

SciPy seems as likely of a culprit but I could be wrong?

But moreso:

> Nengo and Nengo Loihi’s emulator backend are pure Python packages that use NumPy to simulate neural models quickly. On your local machine, you only need to install Nengo Loihi and its dependencies, which include Nengo and NumPy. See Installation for details.

from the [overview](https://www.nengo.ai/nengo-loihi/overview.html).

**Comment by hunse** [comment]
In my experience, Numpy's always the one that's been hard to install, particularly if you want it fast. It's actually much better than it used to be, but it's possible on some systems it may still be a bit tricky to hook up to whatever BLAS library you want to use.

I've never had a problem installing Scipy once Numpy is installed. The main thing I could see going wrong there is it does have a bunch of C and Fortran code, so if for some reason you had to install from source you'd need to have working C and Fortran compilers installed. But I've never had this happen to me, since so many systems some precompiled version available now.

**Comment by arvoelke** [comment]
Relatedly, `python 3.5.2` is no longer in the standard `conda` channel, and so this is a reminder to update the installation documentation (to suggest adding the `conda-forge` channel).

**Comment by hunse** [comment]
Note: The command to add the conda-forge channel with python 3.5.2 is `conda config --add channels confa-forge`

**Comment by arvoelke** [comment]
This looks resolved now in the 0.10.0 release. :)
